routes/web.php
<?php

use App\Http\Controllers\BookingController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TableController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware'=>['auth']],function (){
    Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::resource('tables', TableController::class);
    Route::get('booking/create/{id}', [BookingController::class, 'create'])->name('booking.create');
    Route::post('booking/create', [BookingController::class, 'store'])->name('booking.store');
});

require __DIR__.'/auth.php';

app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use App\Models\Table;
use App\Http\Requests\TableRequest;
use Illuminate\Http\Request;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['tables'] = Table::all();

        return view('table.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('table.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\TableRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TableRequest $request)
    {
        $table = Table::create([
            'name' => $request->get('name'),
        ]);
        if(empty($table)) {
            return redirect()->back()->withInput()->with("ERROR", __('Failed to created'));
        }
        return redirect()->route('tables.index')->with("SUCCESS", 'Table created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function show(Table $table)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function edit(Table $table)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Table $table)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function destroy(Table $table)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/table/_form.blade.php
<div class="mb-4">
    <label class="block" for="task">Table Name</label>
    <input class="focus" type="text" name="name" id="name" value="{{ old('name') }}">
    <p class="text-red-600">{{ $errors->first('name') }}</p>
</div>
<button class="px-4 py-2 bg-green-600" type="submit">{{ $buttonText }}</button>

resources/views/table/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Table') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('tables.store') }}" method="post">
                    @csrf
                    @include('table._form', ['buttonText' => __('Create')])
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/table/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Table List') }}
            </h2>
            <a href="{{ route('tables.create') }}" class="px-4 py-2 bg-green-600">Create Table</a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <section class="container mx-auto p-6 font-mono">
                        <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
                            <div class="w-full overflow-x-auto">
                            <table class="w-full">
                                <thead>
                                <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
                                    <th class="px-4 py-3">ID</th>
                                    <th class="px-4 py-3">Table Name</th>
                                    <th class="px-4 py-3">Action</th>
                                </tr>
                                </thead>
                                @forelse($tables as $table)
                                <tbody class="bg-white">
                                <tr class="text-gray-700">
                                    <td class="px-4 py-3 border">{{ $table->id }}</td>
                                    <td class="px-4 py-3 font-semibold border text-ms">{{ $table->name }}</td>
                                    <td class="px-4 py-3 text-xs border">
                                        <a class="px-2 py-1 bg-yellow-500" href="">Edit</a>
                                        <a class="px-2 py-1 bg-red-500 delete-row" data-confirm="Are you sure to delete this?" href="">Delete</a>
                                    </td>
                                </tr>
                                </tbody>
                                @empty
                                <tr>
                                    <td colspan="3" class="px-4 py-3 text-center">{{ __('No Table Found') }}</td>
                                </tr>
                                @endforelse
                            </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>